# Generated by Django 5.1.4 on 2025-01-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Territorie',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('color', models.CharField(max_length=8)),
                ('geometry', models.TextField()),
            ],
        ),
    ]
