# Generated by Django 5.1.4 on 2025-01-04 07:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_geojson_store', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='files/uploads'), upload_to=''),
        ),
    ]
