# Generated by Django 5.1.4 on 2025-01-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_geojson_store', '0003_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esemeny',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('idopont', models.IntegerField()),
                ('leiras', models.TextField()),
                ('geometry', models.TextField()),
            ],
        ),
    ]
