# Generated by Django 5.1.4 on 2025-01-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_geojson_store', '0004_esemeny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='files/uploads/'),
        ),
    ]
