# Generated by Django 5.1.4 on 2025-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_geojson_store', '0005_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='esemeny',
            name='kep',
            field=models.ImageField(null=True, upload_to='test_geojson_store/files/uploads/esemenyek/'),
        ),
    ]
